In [111]:
import pandas as pd
import numpy as np

train = pd.read_csv("kaggle_house_pred_train.csv")
test = pd.read_csv("kaggle_house_pred_test.csv")
all_X = pd.concat((train.loc[:, 'MSSubClass':'SaleCondition'],
                      test.loc[:, 'MSSubClass':'SaleCondition']))

In [112]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [113]:
numeric_feats = all_X.dtypes[all_X.dtypes != "object"].index
all_X[numeric_feats] = all_X[numeric_feats].apply(lambda x: (x - x.mean())
                                                            / (x.std()))
all_X.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0.067320,RL,-0.184443,-0.217841,Pave,NaN,Reg,Lvl,AllPub,Inside,...,-0.285886,-0.063139,NaN,NaN,NaN,-0.089577,-1.551918,0.157619,WD,Normal
1,-0.873466,RL,0.458096,-0.072032,Pave,NaN,Reg,Lvl,AllPub,FR2,...,-0.285886,-0.063139,NaN,NaN,NaN,-0.089577,-0.446848,-0.602858,WD,Normal
2,0.067320,RL,-0.055935,0.137173,Pave,NaN,IR1,Lvl,AllPub,Inside,...,-0.285886,-0.063139,NaN,NaN,NaN,-0.089577,1.026577,0.157619,WD,Normal
3,0.302516,RL,-0.398622,-0.078371,Pave,NaN,IR1,Lvl,AllPub,Corner,...,-0.285886,-0.063139,NaN,NaN,NaN,-0.089577,-1.551918,-1.363335,WD,Abnorml
4,0.067320,RL,0.629439,0.518814,Pave,NaN,IR1,Lvl,AllPub,FR2,...,-0.285886,-0.063139,NaN,NaN,NaN,-0.089577,2.131647,0.157619,WD,Normal

In [114]:
all_X = pd.get_dummies(all_X, dummy_na=True)

In [115]:
all_X = all_X.fillna(all_X.mean())
all_X.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_Oth,SaleType_WD,SaleType_nan,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SaleCondition_nan
0,0.067320,-0.184443,-0.217841,0.646073,-0.507197,1.046078,0.896679,0.523038,0.580708,-0.29303,...,0,1,0,0,0,0,0,1,0,0
1,-0.873466,0.458096,-0.072032,-0.063174,2.187904,0.154737,-0.395536,-0.569893,1.177709,-0.29303,...,0,1,0,0,0,0,0,1,0,0
2,0.067320,-0.055935,0.137173,0.646073,-0.507197,0.980053,0.848819,0.333448,0.097840,-0.29303,...,0,1,0,0,0,0,0,1,0,0
3,0.302516,-0.398622,-0.078371,0.646073,-0.507197,-1.859033,-0.682695,-0.569893,-0.494771,-0.29303,...,0,1,0,1,0,0,0,0,0,0
4,0.067320,0.629439,0.518814,1.355319,-0.507197,0.947040,0.753100,1.381770,0.468770,-0.29303,...,0,1,0,0,0,0,0,1,0,0

In [116]:
print(train.shape)
num_train = train.shape[0]

X_train = all_X[:num_train].as_matrix()
X_test = all_X[num_train:].as_matrix()
y_train = train.SalePrice.as_matrix()

# from sklearn.cross_validation import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, random_state=1)

# print X_train[:5]
# print X_test[:5]
# print y_train[:5]
# print y_test[:5]

(1460, 81)

In [117]:
import matplotlib.pyplot as plt

In [118]:
from sklearn import ensemble
model_RandomForestRegressor = ensemble.RandomForestRegressor(n_estimators=20)#è¿™é‡Œä½¿ç”¨20ä¸ªå†³ç­–æ ‘

In [119]:
model_RandomForestRegressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [120]:
# y_pred = model_RandomForestRegressor.predict(X_test)
# from sklearn import metrics
# # ç”¨scikit-learnè®¡ç®—MSE
# print "MSE:",metrics.mean_squared_error(y_test, y_pred)
# # ç”¨scikit-learnè®¡ç®—RMSE
# print "RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred))

In [121]:
SalePrice = model_RandomForestRegressor.predict(X_test)
from sklearn.model_selection import cross_val_predict
predicted = cross_val_predict(model_RandomForestRegressor, X, y, cv=10)

In [122]:
Id = np.arange(1461,2919 + 1)

In [123]:
Id_column = pd.Series(Id, name='Id')
SalePrice_column = pd.Series(SalePrice, name='SalePrice')

In [124]:
predictions = pd.concat([Id_column, SalePrice_column], axis=1)  
print predictions
import datetime
now = datetime.datetime.now()
predictions.to_csv('housePriceSub' + now.strftime('%Y%m%d%H%M%S') + '.csv' , index=False, sep=',')

        Id  SalePrice
0     1461  134680.00
1     1462  150417.50
2     1463  178596.60
3     1464  181590.00
4     1465  211800.00
5     1466  185570.00
6     1467  166629.50
7     1468  177275.00
8     1469  183451.00
9     1470  115370.00
10    1471  197949.95
11    1472   96307.50
12    1473   97942.50
13    1474  151457.50
14    1475  148894.25
15    1476  345171.30
16    1477  255334.80
17    1478  310278.05
18    1479  261511.60
19    1480  446238.15
20    1481  312876.10
21    1482  205475.00
22    1483  171996.45
23    1484  188944.75
24    1485  178125.00
25    1486  203332.50
26    1487  334494.75
27    1488  239163.50
28    1489  212735.00
29    1490  193745.00
...    ...        ...
1429  2890   78885.00
1430  2891  131572.50
1431  2892   66850.55
1432  2893  104507.50
1433  2894   65565.55
1434  2895  322771.80
1435  2896  295723.05
1436  2897  205985.00
1437  2898  144437.80
1438  2899  226480.00
1439  2900  156897.50
1440  2901  194467.50
1441  2902  184312.00
1442  2903  360513.80
1443  2904  352077.40
1444  2905  103345.00
1445  2906  212770.50
1446  2907  113755.00
1447  2908  130412.50
1448  2909  146558.25
1449  2910   84750.00
1450  2911   85420.00
1451  2912  151517.00
1452  2913   88550.00
1453  2914   84575.00
1454  2915   85225.00
1455  2916   82125.00
1456  2917  161532.50
1457  2918  123437.50
1458  2919  226450.00

[1459 rows x 2 columns]